apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-application-set
spec:
  generators:
    - list:
        elements:
          - cluster: kind-kind
            url: https://kubernetes.default.svc
            name: prod
            overlay: prod
            # annotations: 'notifications.argoproj.io/subscribe.on-deployed.infra-provider: ""'
          # - cluster: in-cluster
          #   url: https://kubernetes.default.svc
          #   name: staging
          #   overlay: staging
  template:
    metadata:
      name: "my-deployment-{{name}}"
      # annotations: { { annotations } }
    spec:
      project: default
      source:
        repoURL: "https://github.com/MimeLyc/argocd-demo.git"
        targetRevision: HEAD
        path: "demo/overlays/{{overlay}}"
        # kustomize:
        #   namePrefix: "{{name}}-"
        #   path: "demo/overlays/{{overlay}}"
      destination:
        server: "{{url}}"
        namespace: "{{name}}"
